### ISSUE TITLE
Fix for no picture on some TVs/monitors

### ISSUE THREAD

**Issue by antibyte** [andykarpov/tang9k-speccy#1]
Please add this to the instructions:
Some monitors and TVs do not show a picture over the Tang Nano HDMI connector.
In this case you need to add a solder bridge.

I did this and now it works on my TV.

![image](https://github.com/andykarpov/tang9k-speccy/assets/441297/c5a170fd-7697-4b45-83d7-d7e38e41baab)

https://www.eevblog.com/forum/fpga/fpga-to-hdmi-variants/msg4613152/#msg4613152

**Comment by andykarpov** [comment]
Ooh, interesting! Thanks a lot for the tip :)

**Comment by andykarpov** [comment]
Done, readme updated
